config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :people, shallow: true do
    resources :hobbies 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
# == Schema Information
#
# Table name: hobbies
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  kind        :integer
#  person_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Hobby < ApplicationRecord
  belongs_to :person
  enum kind: { indoor: 0, outdoor: 1 }
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  birtdate   :date
#  gender     :integer
#  dni        :integer
#  customer   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Person < ApplicationRecord
  has_many :hobbies
  enum gender: { male: 0, female: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
  end

  def new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

end
def person_params
  params.require(:person).permit(:name, :email)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LaClaseDeHoy
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/people/index.html.haml
%table{:border => "1"}
  %thead
    %tr
      %th Name
      %th email 
      %th birtdate 
      %th gender
      %th dni
      %th customer

  %tbody 
    - @people.each do |person|
      %tr 
        %td 
          = person.name
        %td 
          = person.email
        %td 
          = person.birtdate
        %td
          = person.gender
        %td
          = person.dni
        %td
          = person.customer

%br/
= link_to('New Person', new_person_path)

app/views/people/new.html.haml
%form{:action => "#{people_path}", :method => "post", :border => "1"}
  %input{type: 'hidden', value: form_authenticity_token, name: 'authenticity_token'}
  
  .field
    %label Name
    %input{type: "text", name: "person[name]"}
  .field
    %label Email
    %input{type: "email", name: "person[email]"}/

  .button
    %button{:type => "submit"} Send your message